# Use the official Node.js image as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /src

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Expose the port your application is listening on
EXPOSE 8080

# Start the application when the container starts
CMD ["node", "app.js"]
