name: Server pipeline

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    env:
      GCP_REGION: us-central1
      GCP_REPOSITORY: hb2
      GCP_PROJECT_ID: hannahsbooks
      IMAGE_TAG: ${{ format('api:{0}', github.sha) }}

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate with GCP
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set Docker image URL
      run: |
        echo "IMAGE_URL=$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$IMAGE_TAG" >> $GITHUB_ENV

    - name: Configure Docker 
      run: |
        gcloud auth configure-docker "$GCP_REGION-docker.pkg.dev" --quiet

    - name: Build and tag Docker image
      run: |
        cd ./api_new/src
        docker build -t "$IMAGE_TAG" api/
        docker tag "$IMAGE_TAG" "$IMAGE_URL"

    - name: Push image to GCP Artifact Registry
      run: |
        docker push "$IMAGE_URL"

    - name: Push to Cloud Run
      id: cloud-run-deploy
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'rental-app-api'
        region: ${{ env.GCP_REGION }}
        project_id: ${{ env.GCP_PROJECT_ID }}
        image: "$IMAGE_URL"

    - name: Output
      run: 'curl "${{ steps.cloud-run-deploy.outputs.url }}"'
